Made in#15
vladimirshefer/wishlist pull request #29
Opened 2021-04-26 20:16 UTC by Lidiya-prog

Added logo Made-in-Russia
![image](https://user-images.githubusercontent.com/76654540/116145009-63fa4600-a6e5-11eb-9d24-60da2029f2a6.png)

2021-04-26 20:25 UTC, vladimirshefer requested changes

2021-04-26 20:25 UTC, vladimirshefer commented on src/components/Footer.vue
> +              src="../../img/img made-in.svg"
это не очень надежная ссылка потому что она относительная, к тому же модержить пробел
посмотри вот тут как сделана ссылка на логотип [ссылка](https://github.com/vladimirshefer/wishlist/blob/19dba6059ca1f56932340b2eae4d88c5f6b5bdab/src/components/Navbar.vue#L7)
там используется в коде `require("@/путь/от/корня")`, который всегда вернет нужную ссылку на ресурс

2021-04-26 20:25 UTC, vladimirshefer commented on src/components/Footer.vue
> +              src="../../img/img made-in.svg"
да, и поправь имя файла с картинкой, убери пробел. 
пусть называется made-in-russia.svg

2021-04-29 17:53 UTC, vladimirshefer commented on src/components/Footer.vue
> +              src="../../img/img made-in.svg"
Название файла все еще не то, и положи его в assets плз рядом с лого

2021-04-30 09:15 UTC, vladimirshefer requested changes
файл должен остаться один из трех. и надо переименовать

2021-05-05 21:05 UTC, Lidiya-prog commented
Fixed link

![image](https://user-images.githubusercontent.com/76654540/117209195-b54db800-adfe-11eb-994a-8e2d5ecfdfc8.png)

2021-05-13 11:17 UTC, Lidiya-prog commented
another pull request was added

2021-05-13 11:17 UTC, closed without merging