Progress bar#22
vladimirshefer/wishlist pull request #32
Opened 2021-05-05 20:57 UTC by Lidiya-prog

2021-05-05 21:03 UTC, Lidiya-prog commented
![image](https://user-images.githubusercontent.com/76654540/117208897-55efa800-adfe-11eb-99e6-686b12572ad6.png)
![image](https://user-images.githubusercontent.com/76654540/117208972-6ef85900-adfe-11eb-85a9-687734d32b4c.png)

2021-05-05 21:06 UTC, vladimirshefer requested changes

2021-05-05 21:06 UTC, vladimirshefer commented on src/components/UserWishlist/ItemEditForm.vue
> +  // computed: {
Закомменченный код

2021-05-05 21:06 UTC, vladimirshefer commented on src/components/pages/Home/FeedItem.vue
> +          class="w-50 mt-2 mb-3"
Тут довольно узкие блоки, думаешь 50 процентов ширины норм? Кажется что растянуть на всю ширину будет лучше

2021-05-06 12:05 UTC, Lidiya-prog commented
![image](https://user-images.githubusercontent.com/76654540/117295366-6ba3b280-ae7c-11eb-8a78-4b9a86544dc8.png)
![image](https://user-images.githubusercontent.com/76654540/117295408-79f1ce80-ae7c-11eb-865f-673985d51fbd.png)

2021-05-10 17:33 UTC, closed without merging