Added ckeckbox  and hiding a field cost
vladimirshefer/wishlist pull request #36
Opened 2021-05-20 19:10 UTC by Lidiya-prog

![image](https://user-images.githubusercontent.com/76654540/119035322-1dcc9580-b9b8-11eb-9a60-d2d804910a87.png)
![image](https://user-images.githubusercontent.com/76654540/119035344-23c27680-b9b8-11eb-969b-d09f72348c44.png)

2021-05-25 19:09 UTC, vladimirshefer requested changes

2021-05-25 19:09 UTC, vladimirshefer commented on src/components/UserWishlist/ItemEditForm.vue
> +    if (this.form.moneyCollected == false)
А если true то что вернется?

2021-05-25 19:09 UTC, vladimirshefer commented on src/components/UserWishlist/ItemEditForm.vue
> +     return !!this.form.isMoneyCollectingEnabled},
Скобку закрывающую на новую строку

2021-05-25 20:58 UTC, dimkasyan commented on src/components/UserWishlist/ItemEditForm.vue
> +  isMoneyCollectingEnabledChoice(){
Переименуй на hasMoneyCollectingEnabledChoice

2021-05-26 08:28 UTC, dimkasyan commented on src/components/UserWishlist/ItemEditForm.vue
> +  isMoneyCollectingEnabledChoice(){
Удали этот метод, если он не используется

2021-05-26 17:12 UTC, vladimirshefer approved these changes

2021-05-26 17:19 UTC, Lidiya-prog commented
![Uploading image.png…]()

2021-05-26 17:58 UTC, merged